# version: '3.8'

# services:
#   # --- AMBIENTE DE PRODUÇÃO (Branch: main) ---
#   # Acessível via: https://moneytrack-api.muriloferreira.dev
#   api_prod:
#     build: .
#     container_name: moneytrack_api_prod
#     restart: always
#     ports:
#       - "3000:3000"
#     environment:
#       - PORT=3000
#       - NODE_ENV=production
#       # 'host.docker.internal' permite que o container fale com o Mongo instalado no seu Windows
#       - MONGODB_URI=mongodb://host.docker.internal:27017/moneytrack_prod
#       - JWT_SECRET=sua_chave_secreta_producao
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     networks:
#       - moneytrack_network

#   # --- AMBIENTE DE DESENVOLVIMENTO (Branch: dev) ---
#   # Acessível via: https://moneytrack-dev-api.muriloferreira.dev
#   api_dev:
#     build: .
#     container_name: moneytrack_api_dev
#     restart: always
#     ports:
#       - "3001:3000" # Mapeia a porta 3001 do Windows para a 3000 do container
#     environment:
#       - PORT=3000
#       - NODE_ENV=development
#       - MONGODB_URI=mongodb://host.docker.internal:27017/moneytrack_dev
#       - JWT_SECRET=sua_chave_teste_dev
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     networks:
#       - moneytrack_network

# networks:
#   moneytrack_network:
#     driver: bridge


version: '3.8'

services:
  # O Docker só vai subir o serviço se a variável for passada
  api:
    build: .
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=3000
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=mongodb://host.docker.internal:27017/${DB_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - moneytrack_network

networks:
  moneytrack_network:
    driver: bridge